metricbeat.modules:
- module: system
  enabled: false

- module: elasticsearch
  hosts: ${ELASTIC_HOSTS_LIST_TO_MONITOR}
  xpack.enabled: true
  period: 10s
  scope: node
  username: ${REMOTE_MONITORING_USER}
  password: ${REMOTE_MONITORING_USER_PASSWORD}
  ssl.certificate_authorities: "/usr/share/metricbeat/ca.crt"

- module: logstash
  metricsets: 
    - node
    - node_stats
  hosts: ${LOGSTASH_HOSTS_LIST}
  xpack.enabled: true
  period: 10s
  scope: node
  username: ${REMOTE_MONITORING_USER}
  password: ${REMOTE_MONITORING_USER_PASSWORD}

- module: kibana
  hosts: ["https://kibana1:5601","https://kibana2:5601"]
  xpack.enabled: true
  period: 10s
  scope: node
  username: ${REMOTE_MONITORING_USER}
  password: ${REMOTE_MONITORING_USER_PASSWORD}
  ssl.certificate_authorities: "/usr/share/metricbeat/ca.crt"
  ssl.verification_mode: none

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS_LIST}
  protocol: https
  username: ${BEATS_SYSTEM_USERNAME}
  password: ${BEATS_SYSTEM_PASSWORD}
  ssl.certificate_authorities: "/usr/share/metricbeat/ca.crt"