metricbeat.modules:
- module: system
  enabled: true
  metricsets:
    - cpu
    - load
    - memory
    - network
    - uptime
    - filesystem
    # - diskio # depricated
    - fsstat
  period: 60s
  #processes: ['.*"]
  cpu.metrics: ["percentages", "normalized_percentages"]
  core.metrics: ["percentages"]
  filesystem.ignore_types: [nsfs, sysfs, tmpfs, bdev, proc, cgroup, cgroup2, cpuset, devtmpfs, configfs, debugfs, tracefs, securityfs, sockfs, bpf, pipefs, ramfs, hugetlbfs, devpts, ecryptfs, fuse, fusectl, mqueue, pstore, autofs, binfmt_misc, overlay, autofs, aufs]

- module: linux
  metricsets:
    - iostat

output.elasticsearch:
  enabled: '${OUTPUT_ELASTIC_ENABLED}'
  hosts: '${ELASTIC_HOSTS_LIST}'
  protocol: https
  username: '${BEATS_SYSTEM_USERNAME}'
  password: '${BEATS_SYSTEM_PASSWORD}'
  ssl.verification_mode: "none"
  ssl.certificate_authorities: "/usr/share/metricbeat/ca.crt"
  index: "metricbeat-system"

setup.template:
  #enabled: true
  #overwrite: true
  name: "metricbeat-system"
  pattern: "metricbeat-system"

output.logstash:
  enabled: '${OUTPUT_LOGSTASH_ENABLED}'
  hosts: '${LOGSTASH_HOSTS_LIST}'
  loadbalance: true

#setup.ilm.enabled: true
#setup.ilm.overwrite: true

# load dashboards
##setup.kibana:
## host: "https://kibana:5601" '
## protocol: https
## ssl.certificate_authorities: "/usr/share/metricbeat/ca.crt"
## username:
## password:
##setup.dashboards.enabled: true
 
# debug
# logging.level: debug
output.console:
  enabled: '${OUTPUT_CONSOLE_ENABLED}'
  pretty: true

# disable metrics logging
logging.metrics.enabled: false