apm-server:
  host: "0.0.0.0:8200"
  kibana:
    enabled: true
    host: "https://kibana:5601"
    ssl.enabled: true
    # ssl.verification_mode: none
    ssl.certificate_authorities: "/usr/share/apm-server/config/certs/ca.crt"
    protocol: "https"
    username: "kibana_system"
    password: "{{ env "KIBANA_SYSTEM_PASSWORD" }}"

output.elasticsearch:
  hosts: {{ env "ELASTIC_HOSTS_LIST" }}
  protocol: "https"
  username: "elastic"
  password: "{{ env "ELASTIC_PASSWORD" }}"
  indices:
    - index: "apm-8.13.2-sourcemap"
      when.contains:
        processor.event: "sourcemap"
    - index: "apm-8.13.2-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"
    - index: "apm-8.13.2-transaction-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "transaction"
    - index: "apm-8.13.2-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"
    - index: "apm-8.13.2-metric-%{+yyyy.MM.dd}"
      when.contains:
        processor.event:s "metric"
    - index: "apm-8.13.2-onboarding-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "onboarding"
  ssl.enabled: true
  #ssl.verification_mode: none
  ssl.certificate_authorities: "/usr/share/apm-server/config/certs/ca.crt"
  ssl.certificate: "/usr/share/apm-server/config/certs/apm-server.crt"
  ssl.key: "/usr/share/apm-server/config/certs/apm-server.key"